modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL-3.0-only"
issueTrackerURL="${repo}/issues"

[[mods]]
modId = "invmove"
version = "${version}"
displayName = "InvMove"
displayURL="${repo}"
authors = "PieKing1215"
logoFile = "icon.png"
description = '''${description}'''

[[dependencies.invmove]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"