modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"
issueTrackerURL="${repo}/issues"

[[mods]]
modId = "invmove"
version = "${version}"
displayName = "InvMove"
displayURL="${repo}"
authors = "PieKing1215"
logoFile = "icon.png"
description = '''${description}'''
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config = "invmove.mixins.json"
[[mixins]]
config = "invmove-forge.mixins.json"

[[dependencies.invmove]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove]]
modId = "cloth_config"
mandatory = true
versionRange = "[15,)"
ordering = "NONE"
side = "CLIENT"